# ifndef EPOS2_CONST_V2_H
# define EPOS2_CONST_V2_H

# define EPOS2_BAUDRATE 115200

typedef enum {
	INTERPOLATED_POSITION_MODE=7,
	HOMING_MODE=6,
	PROFILE_VELOCITY_MODE=3,
	PROFILE_POSITION_MODE=1,
	POSITION_MODE=-1,
	VELOCITY_MODE=-2,
	CURRENT_MODE=-3,
	DIAGNOSTIC_MODE=-4,
	MASTER_ENCODER_MODE=-5,
	DIRECTION_MODE=-6
}OPERATION_MODES;

typedef enum {
	DC_MOTOR=1,
	SIN_EC_MOTOR=10,
	TRAPEZOID_EC_MOTOR=11,
	MANUFACTURE_EC_MOTOR=65535
}MOTOR_TYPES;

typedef enum {
	TRAPEZOIDAL_PROFILE=0,
	SINUSOIDAL_PROFILE=1
}MOTION_PROFILES;

typedef enum {
	CLOCKWISE_ROTATION=0,
	ANTICLOCKWISE_ROTATION=1
}EPOS2_MOTOR_ROTATIONS;

typedef enum {
	ABSOLUTE_POSITION=0x1F,
	ABSOLUTE_POSITION_NOW=0x3F,
	RELATIVE_POSITION=0x5F,
	RELATIVE_POSITION_NOW=0x7F
}POSITION_TYPES;


# endif
